import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import "./normalize.css"

//Importaciones personales
import NavBar from "@/components/NavBar";

const fuente = Roboto({
  weight : ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style : "normal",
  subsets : ["latin"],

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={fuente.className}
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
