import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import "./normalize.css"


//Importaciones personales
import NavBar from "@/components/NavBar";
import FooterPage from "@/components/Footer"
import SocialMedia from "@/components/SocialMedia";

const fuente = Roboto({
  weight : ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style : "normal",
  subsets : ["latin"],

});

export const metadata: Metadata = {
  title: "Eddy Lopez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fuente.className} flex flex-col min-h-screen`}
      >
        <NavBar/>
        <main className="flex-grow">
          {children}
        </main>

        <SocialMedia />
        <FooterPage/>
      </body>
    </html>
  );
}
